# This example shows how to download a model from a remote location.
#
# Execute command: helmfile -f examples/rasa/download-model-helmfile.yaml sync
#
repositories:
- name: rasa
  url: https://helm.rasa.com

releases:
  - name: rasa
    chart: rasa/rasa
    values:
      # Expose deployment via LoadBalancer
      - service:
          type: LoadBalancer

      # Enable HTTPS for NGINX (self-signed)
      - nginx:
          tls:
            enabled: true
            generateSelfSignedCert: true

      # Configure Rasa OSS
      - applicationSettings:
          # Enable debug mode
          debugMode: true
          # Don't train an initial model (you're going to download a model, that's why you don't need it)
          trainInitialModel: false
          initialModel: "https://github.com/HussainAli27/rasa-arabic/tree/main/models/20220714-105652-wan-horseradish.tar.gz?raw=true"

          # Credentials configuration
          credentials:
            additionalChannelCredentials:
              # Enable REST channel
              rest:
